#!/usr/bin/env python
# by cyril: cyrilbiz@gmail.com
# parses the file cscVantageLoop.csv generated by the csv extension installed on weewx (see https://github.com/weewx/weewx/wiki/csv)

import datetime
import os
import json
import time
from subprocess import call

vantageLoopFilePath = '/home/admin/wind2web/data/cscVantageLoop.csv'
appspotFilePath     = "/home/admin/wind2web/data/cscWind.txt"
jsonFilePath        = '/home/admin/wind2web/data/cscWind.json'

# read last line of vantageLoop
with open(vantageLoopFilePath) as fp:
    line0 = fp.readline()
    line1 = fp.readline()
    
# split commas
keys = line0.split (",")
vals = line1.split(",")
    
# indexes
dateTimeIdx    = keys.index('# dateTime')
windSpeed10Idx = keys.index('windSpeed10')
windDirDegIdx  = keys.index('windDir')
windGustIdx    = keys.index('windGust')
    
# get data from  list
dateTime      = str(datetime.datetime.fromtimestamp(float(vals[dateTimeIdx] ) ))
dateTimeUnix  = vals[dateTimeIdx] 
dateTimeIso   = str(datetime.datetime.fromtimestamp( float(vals[dateTimeIdx]) ).isoformat()) + 'UTC-7 hours'

    
windSpeed10     = vals[windSpeed10Idx] #wind past 10 seconds (as per vantage doc regarding Loop data
windDirDeg      = vals[windDirDegIdx]
    
if (windDirDeg != 'None'):
    windDirDegFloat    = float(windDirDeg)
else:
    windDirDegFloat = 0

windGust        = vals[windGustIdx]
sectors         =  ["N","NNE","NE","ENE","E","ESE","SE","SSE","S","SSW","SW","WSW","W","WNW","NW","NNW","N"]
windDirSec      = sectors[int(windDirDegFloat/22.5)]

windSpeedStr    =  ' wind speed | ' + windSpeed10 + ' | knots | ' + dateTimeUnix + '\n'
windDirDegStr   = ' wind direction | ' + windDirDeg + ' | degrees | ' + dateTimeUnix + '\n'
windDirSecStr   = ' wind direction | ' +  windDirSec + ' | sector | ' + dateTimeUnix + '\n'
windGustStr     =  ' wind gust speed | ' + windGust + ' | knots | ' + dateTimeUnix + '\n'
    
# write to the txt file that will be uploaded to appspot
with open(appspotFilePath,'w') as fp:
    fp.write( windSpeedStr )
    fp.write( windDirDegStr )
    fp.write( windDirSecStr )
    fp.write( windGustStr )




##
## Unused 
##

    
#print( windSpeedStr )
#print( windDirDegStr )
#print( windDirSecStr )
#print( windGustStr )
    
# post the txt file
# the following lines were used at some point to avoid using the .sh script to push to appspot.
# it was neater but it caused problems at some point. keeping them here as reference in case we want to revive them in the future.

#url = 'http://cal-sailing.appspot.com/cam'
#command1 =  'curl -F "windspeed=@' + appspotFilePath + '" -v http://cal-sailing.appspot.com/cam'
#cmd2 = "scp /home/admin/wind2web/data/cscWind.txt kon***@cyril.website:/home3/kon***/public_html/csc/data/"
#argScp = appspotFilePath +  " kon****@cyril.website:/home3/kon***/public_html/csc/data"
#os.system( command1 )
#os.system( cmd2 )
#print cmd2


#cmd = "scp user1@host1:files user2@host2:files"
#call(command2.split(" "))


#subprocess.call(["scp", argScp])

